### ISSUE TITLE
Solve Chinese garbled problem

### ISSUE THREAD

**Issue by guyu0000** [m1dnight/torrent-parser#4]
`
   BByteString :

    @Override
    public String toString()
    {
        return new String(data, Charset.forName("UTF-8"));
    }
`

**Comment by m1dnight** [comment]
Ah, I had not tested this with inputs. Thanks for the update. Mind doing a PR? Otherwise I'll merge it myself.

**Comment by guyu0000** [comment]
> Ah, I had not tested this with inputs. Thanks for the update. Mind doing a PR? Otherwise I'll merge it myself.

PR completed.

**Comment by m1dnight** [comment]
Fixed in https://github.com/m1dnight/torrent-parser/pull/5
